# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: ETC
has_binder: true
has_settings: true
kind: server
labextension_name: '@educational-technology-collective/etc_jupyterlab_nbgrader_validate'
project_short_description: A JupyterLab extension.
python_name: etc_jupyterlab_nbgrader_validate
repository: https://github.com/educational-technology-collective/etc_jupyterlab_nbgrader_validate.git
test: false
